php_variations:
  - name: cli
    default: true
  - name: fpm
  - name: fpm-apache
    supported_os: # Open a discussion on serversideup/php if you want to see Alpine support for fpm-apache (https://github.com/serversideup/docker-php/discussions/66)
      - bookworm
      - trixie
  - name: fpm-nginx
  - name: frankenphp
    excluded_minor_versions:
      - "8.2"

php_versions:
  - major: "8"
    minor_versions:
      - minor: "8.2"
        base_os:
          - name: alpine3.23
          - name: alpine3.24
          - name: bookworm
          - name: trixie
        patch_versions:
        #   - 8.2.32 # Pull latest from Official PHP source
      - minor: "8.3"
        base_os:
          - name: alpine3.23
          - name: alpine3.24
          - name: bookworm
          - name: trixie
        patch_versions:
          # - 8.3.32 # Pull latest from Official PHP source
      - minor: "8.4"
        base_os:
          - name: alpine3.23
          - name: alpine3.24
          - name: bookworm
          - name: trixie
        patch_versions:
        #   - 8.4.23 # Pull latest from Official PHP source
      - minor: "8.5"
        base_os:
          - name: alpine3.23
          - name: alpine3.24
          - name: bookworm
          - name: trixie
        patch_versions:
        #   - 8.5.8 # Pull latest from Official PHP source

operating_systems:
  - family: alpine
    versions:
      - name: "Alpine 3.23"
        version: alpine3.23
        number: 3.23
        nginx_version: 1.30.4-r1
      - name: "Alpine 3.24"
        version: alpine3.24
        number: 3.24
        nginx_version: 1.30.4-r1
  - family: debian
    default: true
    versions:
      - name: "Debian Bookworm"
        version: bookworm
        number: 12
        nginx_version: 1.30.4-1~bookworm
      - name: "Debian Trixie"
        version: trixie
        number: 13
        nginx_version: 1.30.4-1~trixie
