#!/usr/bin/with-contenv bash

# Check to see if an Artisan file exists and assume means Laravel is configured.
if [ -f $WEBUSER_HOME/artisan ]; then
    ############################################################################
    # Environment detection
    ############################################################################
    APP_ENV_SETTING=$(cat $WEBUSER_HOME/.env | grep APP_ENV | cut -f2 -d"=")

    # If Laravel is not running in development or CI, then automate some production tasks
    if [ "$APP_ENV_SETTING" != "local" ] && [ ! -z $APP_ENV_SETTING ] && [ ${CI_ENV:="false"} != "true" ] ; then
        # ############################################################################
        # # Cache management - commented out for now because of a bug with Laravel caching & API Rate limiting
        # ############################################################################
        # echo "♻️ Refreshing cache..."
        # # Clear cache
        # php $WEBUSER_HOME/artisan cache:clear

        # # Set cache
        # php $WEBUSER_HOME/artisan route:cache
        # php $WEBUSER_HOME/artisan view:cache

        ############################################################################
        # Automated database migrations
        ############################################################################
        if grep -q DB_DATABASE $WEBUSER_HOME/.env; then
            echo "🚀 Running migrations..."
            php $WEBUSER_HOME/artisan migrate --force
        fi

        ############################################################################
        # Automated storage linking
        ############################################################################
        echo "🔐 Linking the storage..."
        php $WEBUSER_HOME/artisan storage:link
    else
        echo "👉 Skipping Laravel production commands because the env is set to 'local' or running in CI..."
    fi
fi