#!/usr/bin/with-contenv bash

#########################################
# Simulate a cron for task schedulers with an infinite loop
#
if [[ $TASK_SCHEDULER_CONTAINER && $TASK_SCHEDULER_CONTAINER == true ]]; then
    echo "⏰ Executing task scheduler... The command 'artisan schedule:run' will execute every 60 seconds."
    # Start infinite loop
    while [ true ]
    # Run every minute
    do
      php /var/www/html/artisan schedule:run --verbose --no-interaction &
      sleep 60
    done
fi