#!/bin/sh

# Get project directory
PROJECT_DIR="$(git rev-parse --show-toplevel)"

# Run a template build
source $PROJECT_DIR/build.sh

# Add any templates to this commit
git add $PROJECT_DIR/dist/

exit 0