####################################################
# Server Side Up -  PHP 7.4 / FPM-NGINX image 
#####################################################

FROM serversideup/php7.4-fpm

LABEL maintainer="Jay Rogers <jay@serversideup.net>"

RUN echo "7.4-fpm-nginx" > /version-fpm-nginx.txt