####################################################
# Server Side Up -  PHP 7.3 / FPM image 
#####################################################

FROM serversideup/php:7.3-cli

LABEL maintainer="Jay Rogers <jay@serversideup.net>"

RUN echo "7.3-fpm" > /version-fpm.txt