#!/command/with-contenv bash

if [[ $EUID == 0 ]]; then
    # Execute our custom script to check & set the webuser id
    set-webuser-id
fi

if [[ $S6_LOGGING != 1 ]]; then
echo '
--------------------------------------------------------------------
 ____                             ____  _     _        _   _
/ ___|  ___ _ ____   _____ _ __  / ___|(_) __| | ___  | | | |_ __
\___ \ / _ \  __\ \ / / _ \  __| \___ \| |/ _` |/ _ \ | | | |  _ \
 ___) |  __/ |   \ V /  __/ |     ___) | | (_| |  __/ | |_| | |_) |
|____/ \___|_|    \_/ \___|_|    |____/|_|\__,_|\___|  \___/| .__/
                                                            |_|

Brought to you by serversideup.net
--------------------------------------------------------------------'

echo '
🙌 To support Server Side Up projects visit:
https://serversideup.net/sponsor

-------------------------------------
ℹ️ Container Information
-------------------------------------'
if [[ $EUID == 0 ]]; then
echo "👉 Warning: The container is running as 'root'.
The container will run PHP as 'webuser', but
mounted volumes may require manual permissions
changes outside of the container.

Docker user:   $(whoami)
Docker uid:    $(id -u "$(whoami)")
Docker gid:    $(id -g "$(whoami)")
App dir:        $WEB_APP_DIRECTORY

Running PHP as...
Web username:  webuser
Webuser uid:   $(id -u webuser)
Webuser gid:   $(id -g webuser)
-------------------------------------
"
else
echo "Docker user:    $(whoami)
Docker uid:    $(id -u "$(whoami)")
Docker gid:    $(id -g "$(whoami)")
App dir:     $WEB_APP_DIRECTORY
-------------------------------------
"
fi