#!/command/with-contenv bash

PUID=${PUID:-9999}
PGID=${PGID:-9999}
WEBUSER_HOME=${WEBUSER_HOME:-"/var/www/html"}

if [[ $PUID != 9999 || $PGID != 9999 ]]; then
    
    # Change the group ID
    groupmod -o -g "$PGID" webgroup
    
    # Change the User ID
    usermod -o -u "$PUID" webuser
    
    # Make sure the home directory is updated with the proper UID & GID
    chown webuser:webgroup $WEBUSER_HOME
fi

if [[ $S6_LOGGING != 1 ]]; then
echo '
--------------------------------------------------------------------
____                             ____  _     _        _   _
/ ___|  ___ _ ____   _____ _ __  / ___|(_) __| | ___  | | | |_ __
\___ \ / _ \  __\ \ / / _ \  __| \___ \| |/ _` |/ _ \ | | | |  _ \
___) |  __/ |   \ V /  __/ |     ___) | | (_| |  __/ | |_| | |_) |
|____/ \___|_|    \_/ \___|_|    |____/|_|\__,_|\___|  \___/| .__/
                                                            |_|

Brought to you by serversideup.net
--------------------------------------------------------------------'

echo '
To support Server Side Up projects visit:
https://serversideup.net/sponsor
-------------------------------------
GID/UID
-------------------------------------'
echo "
User uid:    $(id -u webuser)
User gid:    $(id -g webuser)
-------------------------------------
"
fi