#!/command/with-contenv bash

if [ "$(id -u)" -e 0 ]; then
    echo "Warning: The container is running as 'root', but will still run PHP as 'webuser'. Mounted volumes may require manual permissions changes outside of the container."

    # Execute our custom script to check & set the webuser id
    set-webuser-id
fi

if [[ $S6_LOGGING != 1 ]]; then
echo '
--------------------------------------------------------------------
 ____                             ____  _     _        _   _
/ ___|  ___ _ ____   _____ _ __  / ___|(_) __| | ___  | | | |_ __
\___ \ / _ \  __\ \ / / _ \  __| \___ \| |/ _` |/ _ \ | | | |  _ \
 ___) |  __/ |   \ V /  __/ |     ___) | | (_| |  __/ | |_| | |_) |
|____/ \___|_|    \_/ \___|_|    |____/|_|\__,_|\___|  \___/| .__/
                                                            |_|

Brought to you by serversideup.net
--------------------------------------------------------------------'

echo '
To support Server Side Up projects visit:
https://serversideup.net/sponsor
-------------------------------------
Container Information
-------------------------------------'
echo "
Username:    $(whoami)
User uid:    $(id -u "$(whoami)")
User gid:    $(id -g "$(whoami)")
App dir:     $WEB_APP_DIRECTORY
-------------------------------------
"
fi