#!/command/with-contenv bash

if [[ $S6_LOGGING != 1 ]]; then
echo '
--------------------------------------------------------------------
 ____                             ____  _     _        _   _
/ ___|  ___ _ ____   _____ _ __  / ___|(_) __| | ___  | | | |_ __
\___ \ / _ \  __\ \ / / _ \  __| \___ \| |/ _` |/ _ \ | | | |  _ \
 ___) |  __/ |   \ V /  __/ |     ___) | | (_| |  __/ | |_| | |_) |
|____/ \___|_|    \_/ \___|_|    |____/|_|\__,_|\___|  \___/| .__/
                                                            |_|

Brought to you by serversideup.net
--------------------------------------------------------------------'

echo '
To support Server Side Up projects visit:
https://serversideup.net/sponsor
-------------------------------------
Non-privileged User Information
-------------------------------------'
echo "
Username:    $(whoami)
User uid:    $(id -u webuser)
User gid:    $(id -g webuser)
App dir:     $WEB_APP_DIRECTORY
-------------------------------------
"
fi