#!/usr/bin/with-contenv bash

if [[ $DEBUG_OUTPUT && $DEBUG_OUTPUT == true ]]; then
    # Set NGINX to debug mode
    sed -i 's/^\terror_log.*/\terror_log \/proc\/self\/fd\/2 debug;/' /etc/nginx/nginx.conf

    # Set PHP FPM to debug mode
    sed -i 's/^;log_level.*/log_level = debug/' /etc/php/8.0/fpm/php-fpm.conf

    # Let us know it is in debug mode
    echo "🔥 NGINX and PHP-FPM are in DEBUG MODE 🔥"

fi