####################################################
# Server Side Up -  PHP 7.4 / FPM image 
#####################################################

FROM serversideup/php:7.4-cli

LABEL maintainer="Jay Rogers <jay@serversideup.net>"

RUN echo "7.4-fpm" > /version-fpm.txt