#!/usr/bin/env bash
set -e

# # Debug mode
# set -o xtrace

# Set the MSMTP configuration
MSMTP_RELAY_SERVER_HOSTNAME=${MSMTP_RELAY_SERVER_HOSTNAME:-"mailhog"}
MSMTP_RELAY_SERVER_PORT=${MSMTP_RELAY_SERVER_PORT:-"1025"}

cat > /etc/msmtprc <<EOL
host ${MSMTP_RELAY_SERVER_HOSTNAME}
port ${MSMTP_RELAY_SERVER_PORT}
logfile -
EOL
unset MSMTP_RELAY_SERVER
unset MSMTP_PORT

#########################################
# Exit on SIGTERM
#
trap "exit" TERM

#########################################
# Run a command or start supervisord
#
if [ $# -gt 0 ];then
    # If we passed a command, run it
    echo "Instead of running Supervisor, I am running the command: $@"
    exec "$@"
else
    # Check to see if an Artisan file exists and assume means Laravel is configured.
    if [ -f /var/www/html/artisan ]; then
        ############################################################################
        # Environment detection
        ############################################################################
        APP_ENV_SETTING=$(cat /var/www/html/.env | grep APP_ENV | cut -f2 -d"=")

        # If Laravel is not running in development or CI, then automate some production tasks
        if [ "$APP_ENV_SETTING" != "local" ] && [ ! -z $APP_ENV_SETTING ] && [ ${CI_ENV:="false"} != "true" ] ; then
            # ############################################################################
            # # Cache management - commented out for now because of a bug with Laravel caching & API Rate limiting
            # ############################################################################
            # echo "♻️ Refreshing cache..."
            # # Clear cache
            # php /var/www/html/artisan cache:clear

            # # Set cache
            # php /var/www/html/artisan route:cache
            # php /var/www/html/artisan view:cache

            ############################################################################
            # Automated database migrations
            ############################################################################
            if grep -q DB_DATABASE /var/www/html/.env; then
                echo "🚀 Running migrations..."
                php /var/www/html/artisan migrate --force
            fi

            ############################################################################
            # Automated storage linking
            ############################################################################
            echo "🔐 Linking the storage..."
            php /var/www/html/artisan storage:link
        else
            echo "👉 Skipping Laravel production commands because the env is set to 'local' or running in CI..."
        fi

        ############################################################################
        # Horizon settings
        ############################################################################
        # Read in if Laravel Horizon variable
        HORIZON_ENABLED_SETTING=$(cat /var/www/html/.env | grep HORIZON_ENABLED | cut -f2 -d"=")

        # Check to see if Horizon is enabled
        if [ "$HORIZON_ENABLED_SETTING" == "true" ]; then
            # Start supervisor WITH Horizon
            exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord-with-horizon.conf
        else
            # Start supervisor normally WITHOUT Horizon
            exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
        fi
    else   
    # Start supervisor with Apache & PHP
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
    fi 
fi