####################################################
# Server Side Up -  PHP 7.3 / FPM-NGINX image 
#####################################################

FROM serversideup/php:7.3-fpm

LABEL maintainer="Jay Rogers <jay@serversideup.net>"

RUN echo "7.3-fpm-nginx" > /version-fpm-nginx.txt