####################################################
# Server Side Up -  PHP 7.3 / CLI image 
#####################################################

FROM ubuntu:20.04

LABEL maintainer="Jay Rogers <jay@serversideup.net>"

RUN echo "7.3-cli" > /version-cli.txt