#!/command/with-contenv sh
response=$(curl --fail --location --insecure --silent --show-error http://localhost:8080/ping)

# Check the response
if [ "$response" = "pong" ]; then
    echo "✅ NGINX + PHP-FPM is running correctly."
    exit 0
else
    echo "❌ There seems to be a failure in checking the NGINX + PHP-FPM. Trying again..."
    exit 1
fi