name: Docker Publish (Dev "Main" Images)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src/**
      - .github/workflows/action_publish-images-**
      - .github/workflows/service_docker-**
      - scripts/**

jobs:
  build-dev-images:
    uses: ./.github/workflows/service_docker-build-and-publish.yml
    with:
      # Set to our development repository
      registry-repositories: "docker.io/serversideup/php-dev"
      tag-prefix: ''
      # Set release type to "latest" for our development if on main, otherwise default to testing
      release-type: latest
      authenticate_with_ghcr: false
    secrets: inherit