name: Docker Publish (Dev Images)

on:
  workflow_dispatch:
  pull_request_target:
    types: [opened, synchronize, reopened]
    paths:
      - src/**
      - .github/workflows/action_publish-images-**
      - .github/workflows/service_docker-**
      - scripts/**
  push:
    branches:
      - main
    paths:
      - src/**
      - .github/workflows/action_publish-images-**
      - .github/workflows/service_docker-**
      - scripts/**

jobs:
  build-dev-images:
    runs-on: ubuntu-latest
    steps:
      - name: Set tag prefix
        id: set_tag_prefix
        run: |
          if [ "${{ github.event_name }}" == "pull_request_target" ]; then
            echo "TAG_PREFIX=${{ github.event.pull_request.number }}-" >> $GITHUB_ENV
          else
            echo "TAG_PREFIX=" >> $GITHUB_ENV
          fi
      - name: Set release type
        id: set_release_type
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "RELEASE_TYPE=latest" >> $GITHUB_ENV
          else
            echo "RELEASE_TYPE=testing" >> $GITHUB_ENV
          fi
      - name: Build and Publish Docker Images
        uses: ./.github/workflows/service_docker-build-and-publish.yml
        with:
          registry-repositories: "docker.io/serversideup/php-dev"
          tag-prefix: ${{ env.TAG_PREFIX }}
          release-type: ${{ env.RELEASE_TYPE }}
          authenticate_with_ghcr: false
        secrets: inherit
