name: Update Docker Hub README

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - README.md

jobs:
  update_container_readme:
    runs-on: ubuntu-24.04
    name: Push README to Docker Hub
    steps:
      - name: git checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKER_HUB_README_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_HUB_README_PASSWORD }}
        with:
          destination_container_repo: serversideup/php
          provider: dockerhub
          short_description: 'Production-ready PHP Docker images optimized for Laravel and WordPress.'
          readme_file: 'README.md'